"""Generate web/tokens.js (token table) and web/font.js (device ASCII font) so the simulator works
by double-clicking web/index.html (no server, no fetch). Games are NOT embedded: the emulator
reads .BAS / .DAT straight from the folder you pick."""
import base64, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB = os.path.join(ROOT, "web")
os.makedirs(WEB, exist_ok=True)


def write(name, text):
    with open(os.path.join(WEB, name), "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


tok = json.load(open(os.path.join(ROOT, "tools", "gvb_tokens.json"), encoding="utf-8"))
tok = {k: {"n": v["n"], "kind": v["kind"]} for k, v in tok.items() if not k.startswith("_")}
write("tokens.js",
      "// generated by tools/build_web.py from tools/gvb_tokens.json - do not edit\n"
      "var GVB_TOKENS = " + json.dumps(tok, ensure_ascii=False) + ";\n"
      "if (typeof module !== 'undefined') module.exports = GVB_TOKENS;\n")

font = open(os.path.join(ROOT, "ref", "arucil", "res", "ascii16.bin"), "rb").read()
write("font.js",
      "// 8x16 ASCII glyphs of the real device (160 chars x 16 bytes, MSB = left pixel).\n"
      "// From arucil/gvbasic-simulator4cpp res/ascii16.bin (MIT, see ref/arucil/LICENSE)\n"
      "var GVB_ASCII16 = \"" + base64.b64encode(font).decode("ascii") + "\";\n"
      "if (typeof module !== 'undefined') module.exports = GVB_ASCII16;\n")

fonts = {}
for key, name in (("gb16", "gbfont16.bin"), ("gb12", "gbfont12.bin"), ("ascii12", "ascii12.bin"), ("pic16", "image16.bin")):
    fonts[key] = base64.b64encode(open(os.path.join(ROOT, "ref", "arucil", "res", name), "rb").read()).decode("ascii")
write("fonts.js",
      "// generated by tools/build_web.py from ref/arucil/res/*.bin (arucil/gvbasic-simulator4cpp, MIT, see ref/arucil/LICENSE) - do not edit\n"
      "// the device's 16x16 and 12x12 GB2312 fonts, its 6x12 ASCII font and its 527 pictures (GB codes F8A1-FDD9); read by web/lcdfont.js\n"
      "var GVB_FONTS = " + json.dumps(fonts) + ";\n"
      "if (typeof module !== 'undefined') module.exports = GVB_FONTS;\n")

print("wrote web/tokens.js, web/font.js, web/fonts.js")
